-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.sales_detail
(
    sale_detail_id integer NOT NULL,
    sale_transaction_id integer NOT NULL,
    sale_date date NOT NULL,
    sale_time time without time zone NOT NULL,
    sale_product integer NOT NULL,
    sale_product_quantity integer NOT NULL,
    sale_product_price numeric(8, 2) NOT NULL,
    PRIMARY KEY (sale_detail_id)
);

CREATE TABLE public.sale_transaction
(
    sale_transaction_id integer NOT NULL,
    sale_outlet_id integer NOT NULL,
    staff_id integer NOT NULL,
    customer_id integer NOT NULL,
    total_sale_transaction_price numeric(8, 2) NOT NULL,
    PRIMARY KEY (sale_transaction_id)
);

CREATE TABLE public.products
(
    product_id integer NOT NULL,
    product_type_id integer NOT NULL,
    product_name character varying(100) NOT NULL,
    product_description character varying NOT NULL,
    product_price numeric(8, 2),
    PRIMARY KEY (product_id)
);

CREATE TABLE public.product_type
(
    product_type_id integer NOT NULL,
    product_type character varying(100) NOT NULL,
    product_category character varying(100) NOT NULL,
    PRIMARY KEY (product_type_id)
);

ALTER TABLE public.sales_detail
    ADD FOREIGN KEY (sale_product)
    REFERENCES public.products (product_id)
    NOT VALID;


ALTER TABLE public.sales_detail
    ADD FOREIGN KEY (sale_transaction_id)
    REFERENCES public.sale_transaction (sale_transaction_id)
    NOT VALID;


ALTER TABLE public.products
    ADD FOREIGN KEY (product_type_id)
    REFERENCES public.product_type (product_type_id)
    NOT VALID;

END;