INSERT INTO "DimCustomer"(customerid,category,country,industry)
VALUES
(1,'Individual','Indonesia','Engineering'),
(614,'Individual','United States','Product Management'),
(615,'Individual','China','Services'),
(616,'Individual','Russia','Accounting'),
(617,'Individual','Chile','Business Development'),
(618,'Individual','Nicaragua','Human Resources'),
(41,'Company','Brazil','Marketing'),
(619,'Individual','Russia','Business Development'),
(620,'Individual','China','Business Development'),
(956,'Individual','Peru','Research and Development'),
(621,'Individual','Angola','Services'),
(622,'Individual','Poland','Legal'),
(623,'Individual','Italy','Training'),
(624,'Individual','Indonesia','Sales'),
(625,'Individual','Portugal','Services'),
(626,'Individual','Mexico','Engineering'),
(40,'Individual','Portugal','Human Resources'),
(627,'Company','Philippines','Services'),
(628,'Individual','France','Business Development'),
(629,'Company','France','Training'),
(630,'Individual','Indonesia','Services'),
(631,'Company','Poland','Marketing'),
(632,'Company','Brunei','Training'),
(633,'Individual','Russia','Sales'),
(634,'Company','Mexico','Business Development'),
(39,'Company','Ivory Coast','Engineering'),
(613,'Individual','Czech Republic','Sales'),
(955,'Individual','Sudan','Accounting'),
(612,'Individual','Argentina','Product Management'),
(611,'Individual','Uzbekistan','Engineering'),
(591,'Individual','China','Support'),
(592,'Company','Philippines','Training'),
(593,'Company','China','Services'),
(958,'Company','Indonesia','Sales'),
(594,'Individual','Germany','Engineering'),
(595,'Company','Portugal','Legal'),
(44,'Individual','Paraguay','Human Resources'),
(596,'Company','Philippines','Human Resources'),
(597,'Individual','South Africa','Accounting'),
(598,'Company','United Kingdom','Training'),
(599,'Individual','Cyprus','Engineering'),
(600,'Individual','Sweden','Sales'),
(601,'Individual','Nigeria','Training'),
(602,'Individual','China','Human Resources'),
(603,'Individual','Iran','Engineering'),
(43,'Individual','Portugal','Marketing'),
(604,'Individual','Sweden','Human Resources'),
(998,'Individual','China','Engineering'),
(605,'Individual','Philippines','Engineering'),
(606,'Individual','Poland','Marketing'),
(607,'Individual','Philippines','Support'),
(957,'Company','Philippines','Legal'),
(608,'Company','Dominican Republic','Support'),
(609,'Individual','Indonesia','Training'),
(610,'Company','China','Legal'),
(42,'Individual','Poland','Marketing'),
(590,'Company','China','Human Resources'),
(635,'Individual','Czech Republic','Sales'),
(637,'Company','Madagascar','Support'),
(953,'Company','Vietnam','Business Development'),
(663,'Company','Cuba','Research and Development'),
(664,'Company','Poland','Sales'),
(665,'Company','France','Support'),
(35,'Individual','Republic of the Congo','Business Development'),
(666,'Individual','Japan','Legal'),
(667,'Individual','China','Training'),
(668,'Company','France','Services'),
(669,'Individual','Pakistan','Engineering'),
(670,'Individual','Brazil','Sales'),
(671,'Individual','Czech Republic','Support'),
(672,'Individual','Slovakia','Support'),
(673,'Company','China','Product Management'),
(674,'Company','Ukraine','Support'),
(34,'Company','Croatia','Research and Development'),
(675,'Company','France','Marketing'),
(952,'Individual','China','Sales'),
(676,'Individual','Lithuania','Accounting'),
(677,'Individual','Dominican Republic','Human Resources'),
(678,'Company','China','Product Management'),
(679,'Individual','Latvia','Support'),
(680,'Company','France','Services'),
(681,'Individual','Mauritius','Accounting'),
(33,'Individual','China','Business Development'),
(682,'Company','China','Sales'),
(662,'Individual','Nigeria','Training'),
(636,'Company','Tanzania','Legal'),
(661,'Company','China','Services'),
(659,'Individual','Poland','Engineering'),
(638,'Company','Colombia','Support'),
(639,'Individual','Finland','Legal'),
(640,'Company','Colombia','Support'),
(641,'Individual','Vietnam','Engineering'),
(642,'Company','China','Business Development'),
(38,'Individual','Philippines','Sales'),
(643,'Company','Egypt','Support'),
(644,'Individual','Slovenia','Legal'),
(645,'Individual','Indonesia','Human Resources'),
(646,'Individual','Portugal','Sales');